### ISSUE TITLE
Lectura de XML

### ISSUE THREAD

**Issue by noeldap93** [noeldap93/CFDI-Excel#16]
Una función que reciba el nombre del archivo a leer y retorne una promesa que al resolver pase el contenido del archivo UTF-8 en un string.

Se recomienda crear un modulo con nombre **fileUtils** que contenga esta funcion **readFile** y agregar la funcion **loadFileList**.

Funcionamiento esperado:
``` javascript
fileUtils.readFile("./directory/file.xml").then( function (xmlString) {
    ...
));
```

**Comment by eliu18** [comment]
#20
