### ISSUE TITLE
El test de getRows debe ser independiente de CFDIParse

### ISSUE THREAD

**Issue by noeldap93** [noeldap93/CFDI-Excel#23]
El [test de getRow](https://github.com/noeldap93/CFDI-Excel/blob/ac6312a6ec05cdf749a4782d1b3585d009d61bd8/test/getRow.test.js) falla cuando hay cambios en la clase de CFDIParse

**Comment by noeldap93** [comment]
Utilizar un mock

**Comment by CesarNietoMtz** [comment]
Se cierra Issue de accuerdo a los establecido en #29
